server:
  port: 0

ShoppingCart:
  api:
    prefix: /api/v1/shopping-cart # Префикс url ShoppingCartController

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: dbuser
    password: 12345
    url: jdbc:postgresql://localhost:6544/shopping_cart
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
  sql:
    init:
      mode: always