kafka:
  config:
    bootstrap-address: localhost:9092
    close-client-timeout-sec: 10
    hub-consumer:
      client-id: hub-consumer
      group-id: analyzer-hub-group
      topics:
        - telemetry.hubs.v1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.yandex.practicum.avro.HubEventDeserializer
      poll-timeout-sec: 5
    snapshot-consumer:
      client-id: snapshot-consumer
      group-id: analyzer-snapshot-group
      topics:
        - telemetry.snapshots.v1.
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.yandex.practicum.avro.SensorSnapshotDeserializer
      poll-timeout-sec: 5





#kafkaServer=localhost:9092
#snapshotTopic=telemetry.snapshots.v1
#sensorEventTopic=telemetry.sensors.v1
#hubEventTopic=telemetry.hubs.v1
#
#pollTimeoutMs=5000
#closeClientTimeoutSec=5
#analyzerSnapshotConsumerId=analyzer-snapshot-consumer
#analyzerSnapshotConsumerGroupId=analyzer-snapshot-consumer-group
#analyzerHubEventConsumerId=analyzer-hub-event-consumer
#analyzerHubEventConsumerGroupId=analyzer-hub-event-consumer-group